# Generated by Django 4.2.8 on 2023-12-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("home_page", models.URLField(blank=True)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_comment",
                    models.ManyToManyField(
                        blank=True, related_name="replies", to="comments.comment"
                    ),
                ),
            ],
        ),
    ]
